// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 rewritesplitwords() ", "[example]")
{

	string filename = "allstates.txt";
	string state, name;
	char gen;
	int year, cnt;
	ifstream ifs;
	int count;
	char delimiter = ',';

	count = rewritesplitwords(filename, delimiter);

	REQUIRE(count == 4080);
	cout << "--------------------------------------------------\n";
}

TEST_CASE("Ex2 rewritesplitwords() ", "[example]")
{

	ifstream ifs;
	string state, name;
	char gen;
	int year, cnt;
	int maxINcnt = 0, maxDEcnt = 0;

	ifs.open("split.txt");
	if (!ifs)
		cerr << "File Open Error\n";

	while (ifs >> state >> gen >> year >> name >> cnt)
	{
		// cout << state << "\t" << gen << "\t" << year << "\t" << name << "\t" << cnt << endl;
		if (state == "IN" and year == 2011 and gen == 'F')
		{
			cout << state << "\t" << gen << "\t" << year << "\t" << name << "\t" << cnt << endl;
			if (maxINcnt < cnt)
				maxINcnt = cnt;
		}
		if (state == "DE" and year == 2018 and gen == 'M')
		{
			cout << state << "\t" << gen << "\t" << year << "\t" << name << "\t" << cnt << endl;
			if (maxDEcnt < cnt)
				maxDEcnt = cnt;
		}
	}

	REQUIRE(maxINcnt == 453);
	REQUIRE(maxDEcnt == 63);
	cout << "--------------------------------------------------\n";
}

TEST_CASE("Ex3 MFN() ", "[example]")
{

	ifstream ifs;
	string state, name;
	char gen;
	int year, cnt;
	string retname;

	ifs.open("split.txt");
	if (!ifs)
		cerr << "File Open Error\n";

	retname = MFN("IN", 2018);
	REQUIRE(retname == "Oliver");
	retname = MFN("DE", 2018);
	REQUIRE(retname == "Liam");

	cout << "--------------------------------------------------\n";
}
